#!/bin/sh
#
#  Copyright (C) CFEngine AS
#
#  This file is part of CFEngine 3 - written and maintained by CFEngine AS.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation; version 3.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA
#
# To the extent this program is licensed as part of the Enterprise
# versions of CFEngine, the applicable Commercial Open Source License
# (COSL) may apply to this file if you as a licensee so wish it. See
# included file COSL.txt.
#

#
# Detect and replace non-POSIX shell
#
try_exec() {
  type "$1" > /dev/null 2>&1 && exec "$@"
}

unset foo
(: ${foo%%bar}) 2> /dev/null
T1="$?"

if test "$T1" != 0; then
  try_exec /usr/xpg4/bin/sh "$0" "$@"
  echo "No compatible shell script interpreter found."
  echo "Please find a POSIX shell for your system."
  exit 42
fi

#
# Explicitly use POSIX tools if needed
#
if [ -f /usr/xpg4/bin/grep ]; then
  PATH=/usr/xpg4/bin:$PATH
  export PATH
fi

TEST_DIR="$(dirname $0)"
case "$TEST_DIR" in
    /*)
        ;;
    *)
        TEST_DIR="$(pwd)/$TEST_DIR"
        ;;
esac

if ! test -f "$TEST_DIR/testall.env"; then
    echo "The testall.env file needs to exist in the same directory as $0." 1>&2
    echo "Running 'make check' from the top level will create it." 1>&2
    exit 2
fi

. "$TEST_DIR/testall.env"

"$CORE/tests/acceptance/testall" --agent="$CORE/cf-agent/cf-agent" --cfpromises="$CORE/cf-promises/cf-promises" --cfserverd="$CORE/cf-serverd/cf-serverd" --cfkey="$CORE/cf-key/cf-key" --rpmvercmp="$CORE/ext/rpmvercmp" --include="$TEST_DIR/../../modules" "$@"
