#!/usr/bin/python

import sys
import os
import re

if sys.argv[1] == "supports-api-version":
    sys.stdout.write("1\n")
    sys.exit(0)

module_dir = os.path.dirname(sys.argv[0])

with open(module_dir + "/test_module.log", "a") as log:
    log.write(sys.argv[1] + "\n")

pkg_name = ""
for line in sys.stdin:
    if line.startswith('File='):
        pkg_name = line.split('=', 1)[1].rstrip()
        break

with open(module_dir + "/test_module.log", "r") as log:
    install_found = any(line.find("repo-install") >= 0 for line in log)

if sys.argv[1] == "list-installed":
    if install_found:
        sys.stdout.write("Name=cfe-present-package\nVersion=3\nArchitecture=amd64\n")
    else:
        sys.stdout.write("Name=cfe-present-package\nVersion=1\nArchitecture=amd64\n")

elif sys.argv[1] == "list-updates" or sys.argv[1] == "list-updates-local":
    # Don't print anything if repo-install has been called. We simulate having
    # installed the update.
    if not install_found:
        sys.stdout.write("Name=cfe-present-package\nVersion=3\nArchitecture=amd64\n")

elif sys.argv[1] == "get-package-data":
    sys.stdout.write("PackageType=repo\nName=" + pkg_name + "\n")

sys.exit(0)
