#!/usr/bin/python

import sys
import os
import re

if sys.argv[1] == "supports-api-version":
    sys.stdout.write("1\n")
    exit(0)

module_dir = os.path.dirname(sys.argv[0])

log = open(module_dir + "/test_module.log", "a")
log.write(sys.argv[1] + "\n")
log.close()

pkg_name = ""

for line in sys.stdin:
    match = re.match("^File=(.*)", line)
    if match:
        pkg_name = match.group(1)

if sys.argv[1] == "list-installed":
    sys.stdout.write("Name=cfe-present-package\nVersion=1\nArchitecture=amd64\n")
elif sys.argv[1] == "list-updates" or sys.argv[1] == "list-updates-local":
    log = open(module_dir + "/test_module.log", "r")
    found = False
    for line in log:
        if re.search("repo-install", line):
            found = True
            break
    # Don't print anything if repo-install has been called. We simulate having
    # installed the update.
    if not found:
        sys.stdout.write("Name=cfe-present-package\nVersion=3\nArchitecture=amd64\n")
elif sys.argv[1] == "get-package-data":
    sys.stdout.write("PackageType=repo\nName=" + pkg_name + "\n")

exit(0)
