#!/usr/bin/python

import sys
import os

log = open(os.environ['CFENGINE_TEST_MOCK_LOG'], "a")
log.write("dpkg-deb " + (" ".join(sys.argv[1:])) + "\n")
log.close()

if sys.argv.count("-W"):
    sys.stdout.write('''Name=file_pkg
Version=10.0
Architecture=x86_64
''')
