#!/usr/bin/python

from __future__ import print_function

import sys
import os

log = open(os.environ['CFENGINE_TEST_MOCK_LOG'], "a")
print("dpkg-deb " + (" ".join(sys.argv[1:])), file=log)
log.close()

if sys.argv.count("-W"):
    print('''Name=file_pkg
Version=10.0
Architecture=x86_64''')
