#!/bin/sh

if [ "$1" != "" ]; then
    echo "Regenerate debian packages and debian repository."
    echo "Requires the reprepro tool."
    exit 1
fi

set -e

rm -f deb_repo/*.deb
rm -rf deb_repo/db
rm -rf deb_repo/dists
rm -rf deb_repo/pool

for i in alpha beta charlie; do
    dpkg-deb -b test-package-${i}_1.0-1
    mv -f test-package-${i}_1.0-1.deb deb_repo/test-package-${i}_1.0-1_amd64.deb
done

cd deb_repo
for i in *.deb; do
    REPREPRO_BASE_DIR=`pwd` ../putinrepo.sh $i
done

for i in `find . -name Release`; do
    gpg --detach-sign --armor --no-default-keyring --keyring ../gpg/pubring.gpg --secret-keyring ../gpg/secring.gpg --output $i.gpg $i
done
