#!/bin/sh




if [ "$1" = "" ]; then
    echo "Regenerate rpm packages and rpm repository."
    echo "auto detecting architecture."
    ARCH=$(uname -m)
    echo "Architecture detected as $ARCH."
elif [ "$1" = "i386" ]; then
    echo "Regenerating i386 rpm packages and rpm repository."
    echo "Requires the reprepro tool."
elif [ "$1" = "x86_64" ]; then
    echo "Regenerating x86_64 rpm packages and rpm repository."
    echo "Requires the reprepro tool." 
else 
    echo "Usage: build-deb-repo i386 | x86_64"
    exit 5
fi




set -e

rm -rf rpm_repo
mkdir rpm_repo
mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros

cp test-package-installed.txt ~/rpmbuild/SOURCES

for i in alpha beta charlie; do
    rpmbuild -bb test-package-$i.spec
    cp ~/rpmbuild/RPMS/"$ARCH"/test-package-$i-1.0-1."$ARCH".rpm rpm_repo
done

createrepo rpm_repo
