name: Style Check

on:
  # run this workflow on pull_request activity
  # this includes opening and pushing more commits
  pull_request:
    branches: [ master, 3.18.x, 3.15.x ]

  # run this workflow on push/merge activity
  # pull_request activity won't detect changes
  # in the upstream branch before we merge
  push:
    branches: [ master, 3.18.x, 3.15.x ]

jobs:
  style_check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Style Check
      run: sh tests/style_check.sh
